### PR TITLE
first push for GiggleBot

### PR DESCRIPTION
**Pull request by CleoQc**
No need to merge it right away. 
I'm doing the PR to double check that I did the extension properly.
Feedback appreciated

### CODE REVIEW

**Comment by JoshuaLowe1002** [comment]
Just tested on my PC and looks good to me. So when you've completed stuff, we can get this pushed :)

**Comment by JoshuaLowe1002** [comment]
I've also added back the code in the import generator so it shows up in the python view

**Comment by CleoQc** [comment]
Current status is that all blocks work.
I will revisit every block to make use of shadow blocks where appropriate

**Comment by JoshuaLowe1002** [comment]
Tested all this with Gigglebot. Happy to merge. Thanks for all your hard work @CleoQc!

**Pull request merged**
