### PR TITLE
New Http Requests

### PR DESCRIPTION
**Pull request by Mrpye**
I have added Http client and a code block the code blocks in the basic menu.

I'll keep testing and build up some examples for you.

Just a small note on the node.js port 8080 I had to change to access remotely because it was clashing with another app. changed it to 8081.
You might want to change it back to 8080 or ignore that line of code.

### CODE REVIEW

**Comment by Mrpye** [comment]
OK made the changes to the code block.

In regards to the port, i connected remotely to my PI but UV4L Streaming Server was using that port.
Just thinking might be worth you picking something other that 80, 8080  so you don't clash with apps that use that port.
as 80 and 8080 are used quiet commonly. Just a thought.

**Comment by JoshuaLowe1002** [comment]
Good point. I have accepted this code, i am just testing it now, then i will merge it :)

**Comment by Mrpye** [comment]
Changed the port to 8081

**Comment by JoshuaLowe1002** [comment]
I shall take a look tomorrow with @cjdell

**Comment by Mrpye** [comment]
I have made the menu change.
Also added a comment block in the basic section.

**Pull request merged**
